### ISSUE TITLE
Troubles with setup

### ISSUE THREAD

**Issue by artshevchenko** [softrams/prefect-auth-proxy#6]
Hi! A great idea, this is what is really missing in the open source version of Prefect. 

**Describe the bug**
During the installation process, according to the README (Docker hub image), at the stage of executing the JS code in the browser console, I received the following error in browser console when I tried to execute `let auth = (document.getElementsByTagName('a')[0].__vue__.$store.state)...` (web page contains only "Unauthorized"):
```
Uncaught TypeError: Cannot read properties of undefined (reading '__vue__')
    at <anonymous>:1:50
```

After changing env var `ALLOW_PUBLIC_ACCESS` to `true` I got the following error on the web page:
```
TypeError: Cannot read properties of null (reading 'split')
  at required (/usr/src/app/node_modules/requires-port/index.js:13:23)
  at Object.common.setupOutgoing (/usr/src/app/node_modules/http-proxy/lib/http-proxy/common.js:101:7)
  at Array.stream (/usr/src/app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
  at ProxyServer.<anonymous> (/usr/src/app/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
  at HttpProxyMiddleware.middleware (/usr/src/app/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
When I tried to execute let auth = (document.getElementsByTagName('a') again, I got the same error:
```
Uncaught TypeError: Cannot read properties of undefined (reading '__vue__')
    at <anonymous>:1:50
```

**To Reproduce**
1. Setup Database according to README
2. Setup proxy using pre-built docker image
3. Create API Keys and distribute to users/services according to README
4. Doing "Using API Key via Browser" according to README 
5. See error

**Comment by soham-aiplanet** [comment]
I am facing the same issue, did you find anything to resolve it?
